name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  ci:
    name: CI for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: mkdir build
        run: mkdir build/

      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=Release ..
        working-directory: ./build

      - name: Build
        run: cmake --build . --config Release
        working-directory: ./build

      - name: Test
        run: ctest -C Release
        working-directory: ./build
